### ISSUE TITLE
Test suite missing files

### ISSUE THREAD

**Issue by snoyberg** [prowdsponsor/mangopay#30]
```
Test suite mangopay-tests: RUNNING...
mangopay-tests: hook.test.conf: openBinaryFile: does not exist (No such file or directory)
Test suite mangopay-tests: FAIL
Test suite logged to: /home/stackage/work/logs/nightly/mangopay-1.11.1/test-run.out
```

**Comment by meteficha** [comment]
The `mangopay` test suite requires some setup.  The most difficult part is being accessible from the Internet to receive callbacks.  I could make it run without checking the callbacks but I think it's better for now to just avoid testing it on Stackage.  

So, should I just leave the `mangopay` package on the `expected-test-failures` section or should I make it "gracefully" say that the test suite was okay whenever it doesn't find its configuration?

**Comment by snoyberg** [comment]
Let's just leave it as-is for now. If you'd like to close this issue, feel free to, it's your call whether this is useful to have open or not.

**Comment by meteficha** [comment]
Okay, thanks, let's close it for now.
